# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# ===================================================================

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile" ]
    endpoint:
        health:
            show-details: when_authorized
            roles: 'ROLE_ADMIN'
        jhimetrics:
            enabled: true
    info:
        git:
            mode: full
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
    metrics:
        export:
            # Prometheus is the default metrics backend
            prometheus:
                enabled: true
                step: 60
        enable:
            http: true
            jvm: true
            logback: true
            process: true
            system: true
        distribution:
            percentiles-histogram:
                all: true
            percentiles:
                all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
        tags:
            application: ${spring.application.name}
        web:
            server:
                auto-time-requests: true

spring:
    application:
        name: carcare
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jmx:
        enabled: false
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    mail:
        host: smtp.gmail.com
        port: 587
        username: carcare.noreply@gmail.com
        protocol: smtp
        tls: true
        properties.mail.smtp:
           auth: true
           starttls.enable: true
           ssl.trust: smtp.gmail.com
    messages:
        basename: i18n/messages
    main:
        allow-bean-definition-overriding: true
    mvc:
        favicon:
            enabled: false
    task:
        execution:
            thread-name-prefix: carcare-task-
            pool:
                core-size: 2
                max-size: 50
                queue-capacity: 10000
        scheduling:
            thread-name-prefix: carcare-scheduling-
            pool:
                size: 2
    thymeleaf:
        mode: HTML

server:
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"

springdoc:
    api-docs:
        path: /api-docs
# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    clientApp:
        name: 'carcare'
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: carcare.noreply@gmail.com
    api-docs:
        default-include-pattern: ${server.servlet.context-path:}/api/**
        management-include-pattern: ${server.servlet.context-path:}/management/**
        title: carcare API
        description: carcare API documentation
        version: 1.3.0
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    security:
        content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"

# ===================================================================
# Application specific properties
# ===================================================================

# application:
