version: '2'
services:
    carcare-app:
        image: carcare
        restart: always
        environment:
            #- _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://carcare-mariadb:3306/carcare
            - SPRING_DATASOURCE_PASSWORD=${MARIADB_PASSWORD_ENV}
            - MAIL_PASSWORD=${MAIL_PASSWORD_ENV}
            - MAIL_BASE_URL=46.101.121.29
            - JHIPSTER_SLEEP=5
        volumes:
            - /home/kacper/data/carcare/data:/home/jhipster/data
        expose:
            - "8080"
        depends_on:
            - carcare-mariadb
            - reverseproxy
    carcare-mariadb:
        extends:
            file: mariadb.yml
            service: carcare-mariadb
        restart: always
    reverseproxy:
        image: reverseproxy
        restart: always
        ports:
            - 80:80
            - 3306:3306
