services:
    carcare-app:
        image: registry.gitlab.com/kkasztel_carcare/server/app:1.3.5
        container_name: carcare-app
        restart: always
        environment:
            #- _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,api-docs
            - SPRING_DATASOURCE_URL=jdbc:mariadb://carcare-mariadb:3306/carcare
            - SPRING_DATASOURCE_PASSWORD=${MARIADB_PASSWORD_ENV}
            - MAIL_PASSWORD=${MAIL_PASSWORD_ENV}
            - MAIL_BASE_URL=${MAIL_BASE_URL_ENV}
            - JHIPSTER_SLEEP=5
        volumes:
            - /home/kacper/carcare/data/data:/home/jhipster/data
        expose:
            - "8080"
        depends_on:
            - carcare-mariadb
            - reverseproxy
    carcare-mariadb:
        extends:
            file: mariadb.yml
            service: carcare-mariadb
        restart: always
    reverseproxy:
        image: registry.gitlab.com/kkasztel_carcare/server/proxy:1.3.5
        container_name: carcare-proxy
        restart: always
        ports:
            - 80:80
            - 3306:3306
