version: '2'
services:
    carcare-mariadb:
        image: mariadb:10.3.7
        volumes:
            - ~/data/carcare/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_DATABASE=carcare
        expose:
            - "3306"
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
