image: docker:latest
services:
    - docker:dind
cache:
    paths:
        - .m2/repository
variables:
    IMAGE_NAME_APP: "registry.gitlab.com/kkasztel_carcare/server/app"
    IMAGE_NAME_PROXY: "registry.gitlab.com/kkasztel_carcare/server/proxy"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
stages:
    - test
    - build
    - docker

test:
    stage: test
    image: eclipse-temurin:17
    script:
        - './mvnw test -s .gitlab/ci_settings.xml'
    only:
        - tags
    except:
        - branches
build:
    stage: build
    image: eclipse-temurin:17
    script:
        - './mvnw deploy -s .gitlab/ci_settings.xml -Pprod -DskipTests'
    artifacts:
        paths:
            - target/*.war
    only:
        - tags
    except:
        - branches
app:
    stage: docker
    script:
        - cp target/*.war app.war
        - cp src/main/docker/Dockerfile Dockerfile
        - cp src/main/docker/entrypoint.sh entrypoint.sh
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_NAME_APP .
        - IMAGE_ID=$(docker images | grep $IMAGE_NAME_APP | awk '{print $3}')
        - docker tag $IMAGE_ID $IMAGE_NAME_APP:$CI_COMMIT_TAG
        - docker tag $IMAGE_ID $IMAGE_NAME_APP:latest
        - docker push $IMAGE_NAME_APP:$CI_COMMIT_TAG
        - docker push $IMAGE_NAME_APP:latest
    only:
        - tags
    except:
        - branches
proxy:
    stage: docker
    script:
        - cp src/main/docker/reverseproxy/* .
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_NAME_PROXY .
        - IMAGE_ID=$(docker images | grep $IMAGE_NAME_PROXY | awk '{print $3}')
        - docker tag $IMAGE_ID $IMAGE_NAME_PROXY:$CI_COMMIT_TAG
        - docker tag $IMAGE_ID $IMAGE_NAME_PROXY:latest
        - docker push $IMAGE_NAME_PROXY:$CI_COMMIT_TAG
        - docker push $IMAGE_NAME_PROXY:latest
    only:
        - tags
    except:
        - branches