default:
    image: docker:latest
    services:
        - docker:dind
    cache:
        key:
            files:
                - pom.xml
        paths:
            - .m2/repository
variables:
    IMAGE_NAME_APP: "registry.gitlab.com/kkasztel_carcare/server/app"
    IMAGE_NAME_PROXY: "registry.gitlab.com/kkasztel_carcare/server/proxy"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
stages:
    - test
    - build
    - docker

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
    stage: test
    image: eclipse-temurin:17
    services: []
    script:
        - './mvnw test -s .gitlab/ci_settings.xml'
    rules:
        - if: $CI_COMMIT_TAG
verify:
    stage: test
    image: eclipse-temurin:17
    services: []
    interruptible: true
    script:
        - './mvnw verify -s .gitlab/ci_settings.xml'
    artifacts:
        when: always
        reports:
            junit:
                - target/test-results/test/TEST-*.xml
                - target/test-results/integrationTest/TEST-*.xml
            coverage_report:
                coverage_format: jacoco
                path: target/jacoco/*/jacoco.xml
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
    stage: build
    image: eclipse-temurin:17
    services: []
    script:
        - './mvnw deploy -s .gitlab/ci_settings.xml -Pprod -DskipTests'
    artifacts:
        paths:
            - target/*.war
    rules:
        - if: $CI_COMMIT_TAG
app:
    stage: docker
    script:
        - cp target/*.war app.war
        - cp src/main/docker/Dockerfile Dockerfile
        - cp src/main/docker/entrypoint.sh entrypoint.sh
        - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
        - docker build -t $IMAGE_NAME_APP .
        - IMAGE_ID=$(docker images | grep $IMAGE_NAME_APP | awk '{print $3}')
        - docker tag $IMAGE_ID $IMAGE_NAME_APP:$CI_COMMIT_TAG
        - docker tag $IMAGE_ID $IMAGE_NAME_APP:latest
        - docker push $IMAGE_NAME_APP:$CI_COMMIT_TAG
        - docker push $IMAGE_NAME_APP:latest
    rules:
        - if: $CI_COMMIT_TAG
proxy:
    stage: docker
    script:
        - cp src/main/docker/reverseproxy/* .
        - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
        - docker build -t $IMAGE_NAME_PROXY .
        - IMAGE_ID=$(docker images | grep $IMAGE_NAME_PROXY | awk '{print $3}')
        - docker tag $IMAGE_ID $IMAGE_NAME_PROXY:$CI_COMMIT_TAG
        - docker tag $IMAGE_ID $IMAGE_NAME_PROXY:latest
        - docker push $IMAGE_NAME_PROXY:$CI_COMMIT_TAG
        - docker push $IMAGE_NAME_PROXY:latest
    rules:
        - if: $CI_COMMIT_TAG
